# Generated by Django 5.0.6 on 2024-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('serial', models.CharField(max_length=50, verbose_name='Serial')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('ultimaAsignacion', models.CharField(max_length=100, verbose_name='Ultima Asignación')),
                ('ultimaDesasignacion', models.CharField(max_length=100, verbose_name='Ultima Designación')),
                ('fechaCompra', models.CharField(max_length=100, verbose_name='Fecha de Compra')),
                ('valorCompra', models.CharField(max_length=100, verbose_name='Valor de Compra')),
                ('valorActual', models.CharField(max_length=100, verbose_name='Valor Actual')),
                ('persona', models.CharField(max_length=100, verbose_name='Persona')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('depreciacion', models.CharField(max_length=100, verbose_name='Depreciacion')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
            ],
        ),
    ]
