# Generated by Django 5.0.6 on 2024-06-12 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
